apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-jvm-monitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheuses-k8s
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: user2-jvm-monitor
